version: '3.5'

services:
  php:
    image: registry.gitlab.com/laemmi-dockerimages/php-fpm:7.4
    container_name: laemmi-sync-tools.php
    networks:
      - backend
    depends_on:
      - mysql
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ${PWD}:/var/www/html:cached

  mysql:
    image: mysql:5.7.32
    container_name: laemmi-sync-tools.mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_passwd
    ports:
      - 3306:3306

networks:
  backend: