version: '3.5'

services:
  php:
    image: laemmi/php-fpm:8.1
    depends_on:
      - mysql
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - www_volume:/var/www/html:cached

  mysql:
    image: mysql:5.7
    command: --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_passwd
    ports:
      - "3306:3306"

volumes:
  www_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: .